name: xc
on:
  push:
    branches: [dev, master]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
      - uses: actions/checkout@master

      - run: xmake -P ${{ github.workspace }} -y

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: build/windows/x64/release/xc.exe
          overwrite: true