name: xc build
on:
  push:
    branches: [dev, master]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { runner: windows-latest, os: windows, arch: x64, bin_ext: .exe }
        - { runner: ubuntu-latest,  os: linux,   arch: x86_64 }
        - { runner: ubuntu-latest,  os: linux,   arch: arm64-v8a }

    runs-on: ${{ matrix.platform.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          actions-cache-folder: .xmake-cache

      - name: Configure xmake and install dependencies
        run: xmake config --arch=${{ matrix.platform.arch }} --yes

      - name: Build
        run: xmake -y

      # Nightly tags (for commits to dev branch)
      - name: Upload binaries to release (Dev)
        uses: svenstaro/upload-release-action@v2
        if: ${{ (github.ref == 'refs/heads/dev') && github.event_name == 'push' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ matrix.platform.os }}/${{ matrix.platform.arch }}/release/xc${{ matrix.platform.bin_ext }}
          asset_name: ${{ matrix.platform.os }}-${{ matrix.platform.arch }}-xc${{ matrix.platform.bin_ext }}
          tag: nightly
          overwrite: true
  
      # Release tags (for tags)
      - name: Upload binaries to release (Tag)
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.event.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ matrix.platform.os }}/${{ matrix.platform.arch }}/release/xc*
          asset_name: ${{ matrix.platform.os }}-${{ matrix.platform.arch }}-xc${{ matrix.platform.bin_ext }}
          tag: ${{ github.ref }}
          overwrite: true
